name: Discord2MCPE
version: 1.0.0
main: RTG\Discord2MCPE\Loader
api:
  - 3.0.0-ALPHA7
commands:
  discord:
    description: "Hey World"
    permission: discord.talk
permissions:
  discord.talk:
    default: op