---
# Config
# All rights reserved RTG
username: "MCPE2Discord"
avatar: "http://benjiflaming.com/wp-content/uploads/2010/06/white.png"
url: "https://discordapp.com/api/webhooks/300100506448166913/pu9SVIw4WameOPc4Zo-g10fsf1QL0ZaoDx4TT1j1FUcp_LG3k7HHgje14LZeiVe9Gpxb"
...